volumes:
  mongodbdata:
  cache:
    driver: local

services:
  mongo:
    container_name: stansburyswim-mongo
    image: mongo:6.0.3
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27019:27017
